# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindowUi.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QTextEdit, QWidget)

class Ui_MainWindowUi(object):
    def setupUi(self, MainWindowUi):
        if not MainWindowUi.objectName():
            MainWindowUi.setObjectName(u"MainWindowUi")
        MainWindowUi.resize(1094, 632)
        self.centralwidget = QWidget(MainWindowUi)
        self.centralwidget.setObjectName(u"centralwidget")
        self.labelDetectorMentiras = QLabel(self.centralwidget)
        self.labelDetectorMentiras.setObjectName(u"labelDetectorMentiras")
        self.labelDetectorMentiras.setGeometry(QRect(80, 30, 921, 31))
        font = QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.labelDetectorMentiras.setFont(font)
        self.labelDetectorMentiras.setAlignment(Qt.AlignCenter)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 90, 1091, 521))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.textEdit_2 = QTextEdit(self.tab)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(10, 40, 1061, 441))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.inputPergunta = QLabel(self.tab_2)
        self.inputPergunta.setObjectName(u"inputPergunta")
        self.inputPergunta.setGeometry(QRect(10, 120, 1011, 71))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.inputPergunta.setFont(font1)
        self.inputPergunta.setAlignment(Qt.AlignCenter)
        self.btnBitalinoConnect = QPushButton(self.tab_2)
        self.btnBitalinoConnect.setObjectName(u"btnBitalinoConnect")
        self.btnBitalinoConnect.setGeometry(QRect(10, 20, 161, 31))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(True)
        self.btnBitalinoConnect.setFont(font2)
        self.groupBox = QGroupBox(self.tab_2)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 310, 1071, 141))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 40, 71, 16))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(True)
        self.label.setFont(font3)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(60, 90, 71, 16))
        self.label_2.setFont(font3)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(320, 40, 71, 16))
        self.label_3.setFont(font3)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(590, 40, 141, 16))
        self.label_4.setFont(font3)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(300, 90, 91, 16))
        self.label_5.setFont(font3)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(620, 90, 111, 16))
        self.label_6.setFont(font3)
        self.label_Minimo = QLabel(self.groupBox)
        self.label_Minimo.setObjectName(u"label_Minimo")
        self.label_Minimo.setGeometry(QRect(140, 40, 71, 16))
        font4 = QFont()
        font4.setPointSize(10)
        self.label_Minimo.setFont(font4)
        self.label_Maximo = QLabel(self.groupBox)
        self.label_Maximo.setObjectName(u"label_Maximo")
        self.label_Maximo.setGeometry(QRect(140, 90, 71, 16))
        self.label_Maximo.setFont(font4)
        self.label_Media = QLabel(self.groupBox)
        self.label_Media.setObjectName(u"label_Media")
        self.label_Media.setGeometry(QRect(410, 40, 81, 16))
        self.label_Media.setFont(font4)
        self.label_Mediana = QLabel(self.groupBox)
        self.label_Mediana.setObjectName(u"label_Mediana")
        self.label_Mediana.setGeometry(QRect(410, 90, 81, 16))
        self.label_Mediana.setFont(font4)
        self.label_desvioPadrao = QLabel(self.groupBox)
        self.label_desvioPadrao.setObjectName(u"label_desvioPadrao")
        self.label_desvioPadrao.setGeometry(QRect(740, 40, 81, 16))
        self.label_desvioPadrao.setFont(font4)
        self.label_Variancia = QLabel(self.groupBox)
        self.label_Variancia.setObjectName(u"label_Variancia")
        self.label_Variancia.setGeometry(QRect(740, 90, 81, 16))
        self.label_Variancia.setFont(font4)
        self.label_countdown_questions = QLabel(self.tab_2)
        self.label_countdown_questions.setObjectName(u"label_countdown_questions")
        self.label_countdown_questions.setGeometry(QRect(950, 70, 61, 31))
        self.label_countdown_questions.setFont(font2)
        self.btnStart = QPushButton(self.tab_2)
        self.btnStart.setObjectName(u"btnStart")
        self.btnStart.setGeometry(QRect(180, 20, 141, 31))
        font5 = QFont()
        font5.setPointSize(8)
        font5.setBold(True)
        self.btnStart.setFont(font5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.btn_CalcularResultados = QPushButton(self.tab_3)
        self.btn_CalcularResultados.setObjectName(u"btn_CalcularResultados")
        self.btn_CalcularResultados.setGeometry(QRect(60, 30, 111, 41))
        self.btn_CalcularResultados.setFont(font2)
        self.groupBox_2 = QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(240, 10, 761, 91))
        self.label_Minimo_PR = QLabel(self.groupBox_2)
        self.label_Minimo_PR.setObjectName(u"label_Minimo_PR")
        self.label_Minimo_PR.setGeometry(QRect(230, 20, 55, 16))
        self.label_Media_PR = QLabel(self.groupBox_2)
        self.label_Media_PR.setObjectName(u"label_Media_PR")
        self.label_Media_PR.setGeometry(QRect(420, 20, 55, 16))
        self.label_34 = QLabel(self.groupBox_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(550, 50, 71, 16))
        font6 = QFont()
        font6.setBold(True)
        self.label_34.setFont(font6)
        self.label_Variancia_PR = QLabel(self.groupBox_2)
        self.label_Variancia_PR.setObjectName(u"label_Variancia_PR")
        self.label_Variancia_PR.setGeometry(QRect(640, 50, 55, 16))
        self.label_Maximo_PR = QLabel(self.groupBox_2)
        self.label_Maximo_PR.setObjectName(u"label_Maximo_PR")
        self.label_Maximo_PR.setGeometry(QRect(230, 50, 55, 16))
        self.label_Mediana_PR = QLabel(self.groupBox_2)
        self.label_Mediana_PR.setObjectName(u"label_Mediana_PR")
        self.label_Mediana_PR.setGeometry(QRect(420, 50, 55, 16))
        self.label_desvioPadrao_PR = QLabel(self.groupBox_2)
        self.label_desvioPadrao_PR.setObjectName(u"label_desvioPadrao_PR")
        self.label_desvioPadrao_PR.setGeometry(QRect(640, 20, 55, 16))
        self.label_33 = QLabel(self.groupBox_2)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(520, 20, 111, 16))
        self.label_33.setFont(font6)
        self.label_29 = QLabel(self.groupBox_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(170, 20, 55, 16))
        self.label_29.setFont(font6)
        self.label_32 = QLabel(self.groupBox_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(340, 50, 71, 16))
        self.label_32.setFont(font6)
        self.label_31 = QLabel(self.groupBox_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(330, 20, 71, 16))
        self.label_31.setFont(font6)
        self.label_31.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_30 = QLabel(self.groupBox_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(170, 50, 55, 16))
        self.label_30.setFont(font6)
        self.btn_onePlotData = QPushButton(self.groupBox_2)
        self.btn_onePlotData.setObjectName(u"btn_onePlotData")
        self.btn_onePlotData.setGeometry(QRect(20, 20, 93, 28))
        self.btn_multiPlotData = QPushButton(self.groupBox_2)
        self.btn_multiPlotData.setObjectName(u"btn_multiPlotData")
        self.btn_multiPlotData.setGeometry(QRect(20, 50, 93, 28))
        self.groupBox_3 = QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 110, 1071, 121))
        self.label_Media_RQ1 = QLabel(self.groupBox_3)
        self.label_Media_RQ1.setObjectName(u"label_Media_RQ1")
        self.label_Media_RQ1.setGeometry(QRect(220, 60, 55, 16))
        self.label_RD_RQ1 = QLabel(self.groupBox_3)
        self.label_RD_RQ1.setObjectName(u"label_RD_RQ1")
        self.label_RD_RQ1.setGeometry(QRect(780, 90, 55, 16))
        self.label_desvioPadrao_RQ1 = QLabel(self.groupBox_3)
        self.label_desvioPadrao_RQ1.setObjectName(u"label_desvioPadrao_RQ1")
        self.label_desvioPadrao_RQ1.setGeometry(QRect(400, 60, 55, 16))
        self.label_Resultado_Q1 = QLabel(self.groupBox_3)
        self.label_Resultado_Q1.setObjectName(u"label_Resultado_Q1")
        self.label_Resultado_Q1.setGeometry(QRect(900, 80, 171, 31))
        font7 = QFont()
        font7.setPointSize(12)
        self.label_Resultado_Q1.setFont(font7)
        self.label_46 = QLabel(self.groupBox_3)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(20, 60, 55, 16))
        self.label_46.setFont(font6)
        self.label_65 = QLabel(self.groupBox_3)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(660, 60, 111, 20))
        self.label_65.setFont(font6)
        self.label_65.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_PA_RQ1 = QLabel(self.groupBox_3)
        self.label_PA_RQ1.setObjectName(u"label_PA_RQ1")
        self.label_PA_RQ1.setGeometry(QRect(590, 90, 55, 16))
        self.label_Maximo_RQ1 = QLabel(self.groupBox_3)
        self.label_Maximo_RQ1.setObjectName(u"label_Maximo_RQ1")
        self.label_Maximo_RQ1.setGeometry(QRect(80, 90, 55, 16))
        self.label_60 = QLabel(self.groupBox_3)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(900, 50, 111, 31))
        self.label_60.setFont(font3)
        self.label_41 = QLabel(self.groupBox_3)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(20, 90, 55, 16))
        self.label_41.setFont(font6)
        self.input_ResultadoFinal_Q1 = QLabel(self.groupBox_3)
        self.input_ResultadoFinal_Q1.setObjectName(u"input_ResultadoFinal_Q1")
        self.input_ResultadoFinal_Q1.setGeometry(QRect(20, 20, 981, 21))
        self.input_ResultadoFinal_Q1.setFont(font2)
        self.label_Mediana_RQ1 = QLabel(self.groupBox_3)
        self.label_Mediana_RQ1.setObjectName(u"label_Mediana_RQ1")
        self.label_Mediana_RQ1.setGeometry(QRect(220, 90, 55, 16))
        self.label_44 = QLabel(self.groupBox_3)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(160, 60, 41, 16))
        self.label_44.setFont(font6)
        self.label_Variancia_RQ1 = QLabel(self.groupBox_3)
        self.label_Variancia_RQ1.setObjectName(u"label_Variancia_RQ1")
        self.label_Variancia_RQ1.setGeometry(QRect(400, 90, 55, 16))
        self.label_Minimo_RQ1 = QLabel(self.groupBox_3)
        self.label_Minimo_RQ1.setObjectName(u"label_Minimo_RQ1")
        self.label_Minimo_RQ1.setGeometry(QRect(80, 60, 55, 16))
        self.label_45 = QLabel(self.groupBox_3)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(500, 60, 71, 16))
        self.label_45.setFont(font6)
        self.label_45.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_PT_RQ1 = QLabel(self.groupBox_3)
        self.label_PT_RQ1.setObjectName(u"label_PT_RQ1")
        self.label_PT_RQ1.setGeometry(QRect(590, 60, 55, 16))
        self.label_43 = QLabel(self.groupBox_3)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(320, 90, 71, 16))
        self.label_43.setFont(font6)
        self.label_47 = QLabel(self.groupBox_3)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(150, 90, 71, 16))
        self.label_47.setFont(font6)
        self.label_LAT_RQ1 = QLabel(self.groupBox_3)
        self.label_LAT_RQ1.setObjectName(u"label_LAT_RQ1")
        self.label_LAT_RQ1.setGeometry(QRect(780, 60, 55, 16))
        self.label_63 = QLabel(self.groupBox_3)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(480, 90, 111, 16))
        self.label_63.setFont(font6)
        self.label_63.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_64 = QLabel(self.groupBox_3)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(660, 90, 111, 16))
        self.label_64.setFont(font6)
        self.label_64.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_42 = QLabel(self.groupBox_3)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(290, 60, 101, 16))
        self.label_42.setFont(font6)
        self.groupBox_4 = QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 240, 1071, 121))
        self.label_68 = QLabel(self.groupBox_4)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(500, 60, 71, 16))
        self.label_68.setFont(font6)
        self.label_68.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_54 = QLabel(self.groupBox_4)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(320, 90, 71, 16))
        self.label_54.setFont(font6)
        self.label_Mediana_RQ2 = QLabel(self.groupBox_4)
        self.label_Mediana_RQ2.setObjectName(u"label_Mediana_RQ2")
        self.label_Mediana_RQ2.setGeometry(QRect(220, 90, 55, 16))
        self.input_ResultadoFinal_Q2 = QLabel(self.groupBox_4)
        self.input_ResultadoFinal_Q2.setObjectName(u"input_ResultadoFinal_Q2")
        self.input_ResultadoFinal_Q2.setGeometry(QRect(20, 20, 981, 21))
        self.input_ResultadoFinal_Q2.setFont(font2)
        self.label_51 = QLabel(self.groupBox_4)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(290, 60, 111, 16))
        self.label_51.setFont(font6)
        self.label_PT_RQ2 = QLabel(self.groupBox_4)
        self.label_PT_RQ2.setObjectName(u"label_PT_RQ2")
        self.label_PT_RQ2.setGeometry(QRect(590, 60, 55, 16))
        self.label_Variancia_RQ2 = QLabel(self.groupBox_4)
        self.label_Variancia_RQ2.setObjectName(u"label_Variancia_RQ2")
        self.label_Variancia_RQ2.setGeometry(QRect(400, 90, 55, 16))
        self.label_PA_RQ2 = QLabel(self.groupBox_4)
        self.label_PA_RQ2.setObjectName(u"label_PA_RQ2")
        self.label_PA_RQ2.setGeometry(QRect(590, 90, 55, 16))
        self.label_LAT_RQ2 = QLabel(self.groupBox_4)
        self.label_LAT_RQ2.setObjectName(u"label_LAT_RQ2")
        self.label_LAT_RQ2.setGeometry(QRect(780, 60, 55, 16))
        self.label_69 = QLabel(self.groupBox_4)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(660, 90, 111, 16))
        self.label_69.setFont(font6)
        self.label_69.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_RD_RQ2 = QLabel(self.groupBox_4)
        self.label_RD_RQ2.setObjectName(u"label_RD_RQ2")
        self.label_RD_RQ2.setGeometry(QRect(780, 90, 55, 16))
        self.label_Maximo_RQ2 = QLabel(self.groupBox_4)
        self.label_Maximo_RQ2.setObjectName(u"label_Maximo_RQ2")
        self.label_Maximo_RQ2.setGeometry(QRect(80, 90, 55, 16))
        self.label_Minimo_RQ2 = QLabel(self.groupBox_4)
        self.label_Minimo_RQ2.setObjectName(u"label_Minimo_RQ2")
        self.label_Minimo_RQ2.setGeometry(QRect(80, 60, 55, 16))
        self.label_53 = QLabel(self.groupBox_4)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(900, 50, 111, 31))
        self.label_53.setFont(font3)
        self.label_Media_RQ2 = QLabel(self.groupBox_4)
        self.label_Media_RQ2.setObjectName(u"label_Media_RQ2")
        self.label_Media_RQ2.setGeometry(QRect(220, 60, 55, 16))
        self.label_66 = QLabel(self.groupBox_4)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(660, 60, 111, 20))
        self.label_66.setFont(font6)
        self.label_66.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_67 = QLabel(self.groupBox_4)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(480, 90, 111, 16))
        self.label_67.setFont(font6)
        self.label_67.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_52 = QLabel(self.groupBox_4)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(20, 60, 55, 16))
        self.label_52.setFont(font6)
        self.label_Resultado_Q2 = QLabel(self.groupBox_4)
        self.label_Resultado_Q2.setObjectName(u"label_Resultado_Q2")
        self.label_Resultado_Q2.setGeometry(QRect(900, 80, 171, 31))
        self.label_Resultado_Q2.setFont(font7)
        self.label_49 = QLabel(self.groupBox_4)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(20, 90, 55, 16))
        self.label_49.setFont(font6)
        self.label_50 = QLabel(self.groupBox_4)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(150, 90, 71, 16))
        self.label_50.setFont(font6)
        self.label_desvioPadrao_RQ2 = QLabel(self.groupBox_4)
        self.label_desvioPadrao_RQ2.setObjectName(u"label_desvioPadrao_RQ2")
        self.label_desvioPadrao_RQ2.setGeometry(QRect(400, 60, 55, 16))
        self.label_48 = QLabel(self.groupBox_4)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(160, 60, 71, 16))
        self.label_48.setFont(font6)
        self.groupBox_5 = QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 370, 1071, 121))
        self.label_57 = QLabel(self.groupBox_5)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(150, 90, 71, 16))
        self.label_57.setFont(font6)
        self.label_Resultado_Q3 = QLabel(self.groupBox_5)
        self.label_Resultado_Q3.setObjectName(u"label_Resultado_Q3")
        self.label_Resultado_Q3.setGeometry(QRect(900, 70, 171, 31))
        self.label_Resultado_Q3.setFont(font7)
        self.label_desvioPadrao_RQ3 = QLabel(self.groupBox_5)
        self.label_desvioPadrao_RQ3.setObjectName(u"label_desvioPadrao_RQ3")
        self.label_desvioPadrao_RQ3.setGeometry(QRect(400, 60, 55, 16))
        self.label_Minimo_RQ3 = QLabel(self.groupBox_5)
        self.label_Minimo_RQ3.setObjectName(u"label_Minimo_RQ3")
        self.label_Minimo_RQ3.setGeometry(QRect(80, 60, 55, 16))
        self.label_Mediana_RQ3 = QLabel(self.groupBox_5)
        self.label_Mediana_RQ3.setObjectName(u"label_Mediana_RQ3")
        self.label_Mediana_RQ3.setGeometry(QRect(220, 90, 55, 16))
        self.label_56 = QLabel(self.groupBox_5)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(20, 90, 55, 16))
        self.label_56.setFont(font6)
        self.label_RD_RQ3 = QLabel(self.groupBox_5)
        self.label_RD_RQ3.setObjectName(u"label_RD_RQ3")
        self.label_RD_RQ3.setGeometry(QRect(780, 90, 55, 16))
        self.label_59 = QLabel(self.groupBox_5)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(20, 60, 55, 16))
        self.label_59.setFont(font6)
        self.label_55 = QLabel(self.groupBox_5)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(160, 60, 71, 16))
        self.label_55.setFont(font6)
        self.label_Media_RQ3 = QLabel(self.groupBox_5)
        self.label_Media_RQ3.setObjectName(u"label_Media_RQ3")
        self.label_Media_RQ3.setGeometry(QRect(220, 60, 55, 16))
        self.label_70 = QLabel(self.groupBox_5)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(670, 60, 101, 20))
        self.label_70.setFont(font6)
        self.label_70.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_72 = QLabel(self.groupBox_5)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(500, 60, 81, 16))
        self.label_72.setFont(font6)
        self.label_72.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_61 = QLabel(self.groupBox_5)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(320, 90, 71, 16))
        self.label_61.setFont(font6)
        self.input_ResultadoFinal_Q3 = QLabel(self.groupBox_5)
        self.input_ResultadoFinal_Q3.setObjectName(u"input_ResultadoFinal_Q3")
        self.input_ResultadoFinal_Q3.setGeometry(QRect(20, 20, 981, 21))
        self.input_ResultadoFinal_Q3.setFont(font2)
        self.label_62 = QLabel(self.groupBox_5)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(900, 40, 111, 31))
        self.label_62.setFont(font3)
        self.label_71 = QLabel(self.groupBox_5)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(480, 90, 111, 16))
        self.label_71.setFont(font6)
        self.label_71.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_PT_RQ3 = QLabel(self.groupBox_5)
        self.label_PT_RQ3.setObjectName(u"label_PT_RQ3")
        self.label_PT_RQ3.setGeometry(QRect(590, 60, 55, 16))
        self.label_73 = QLabel(self.groupBox_5)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(660, 90, 111, 16))
        self.label_73.setFont(font6)
        self.label_73.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_Maximo_RQ3 = QLabel(self.groupBox_5)
        self.label_Maximo_RQ3.setObjectName(u"label_Maximo_RQ3")
        self.label_Maximo_RQ3.setGeometry(QRect(80, 90, 55, 16))
        self.label_LAT_RQ3 = QLabel(self.groupBox_5)
        self.label_LAT_RQ3.setObjectName(u"label_LAT_RQ3")
        self.label_LAT_RQ3.setGeometry(QRect(780, 60, 55, 16))
        self.label_Variancia_RQ3 = QLabel(self.groupBox_5)
        self.label_Variancia_RQ3.setObjectName(u"label_Variancia_RQ3")
        self.label_Variancia_RQ3.setGeometry(QRect(400, 90, 55, 16))
        self.label_58 = QLabel(self.groupBox_5)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(290, 60, 111, 16))
        self.label_58.setFont(font6)
        self.label_PA_RQ3 = QLabel(self.groupBox_5)
        self.label_PA_RQ3.setObjectName(u"label_PA_RQ3")
        self.label_PA_RQ3.setGeometry(QRect(590, 90, 55, 16))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.textEdit = QTextEdit(self.tab_4)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(80, 90, 871, 291))
        self.tabWidget.addTab(self.tab_4, "")
        MainWindowUi.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindowUi)
        self.statusbar.setObjectName(u"statusbar")
        MainWindowUi.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowUi)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindowUi)
    # setupUi

    def retranslateUi(self, MainWindowUi):
        MainWindowUi.setWindowTitle(QCoreApplication.translate("MainWindowUi", u"Detector de Mentiras", None))
        self.labelDetectorMentiras.setText(QCoreApplication.translate("MainWindowUi", u"Detector de Mentiras", None))
        self.textEdit_2.setHtml(QCoreApplication.translate("MainWindowUi", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Instru\u00e7\u00f5es para o teste:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1. Coloque os el\u00e9trodos na palma da m\u00e3o</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-botto"
                        "m:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2. Respire normalmente e tente abstrair-se do que lhe rodeia</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\""
                        ">3. Ser\u00e3o usados 15seg antes de iniciar o teste, para fazer criar um padr\u00e3o da sua resposta galv\u00e1nica.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">4. Depois ser\u00e3o apresentadas 3 perguntas ao qual ter\u00e1 15 segundos para responder a cada uma</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; m"
                        "argin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">5. Ap\u00f3s o final das perguntas ser\u00e1 apresentado os resultado do teste</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindowUi", u"Introdu\u00e7\u00e3o", None))
        self.inputPergunta.setText(QCoreApplication.translate("MainWindowUi", u"Perguntas...", None))
        self.btnBitalinoConnect.setText(QCoreApplication.translate("MainWindowUi", u"Conectar Bitalino", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindowUi", u"Dados em tempo real", None))
        self.label.setText(QCoreApplication.translate("MainWindowUi", u"M\u00ednimo:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindowUi", u"M\u00e1ximo:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindowUi", u"M\u00e9dia:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindowUi", u"Desvio-Padr\u00e3o:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindowUi", u"Mediana:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindowUi", u"Vari\u00e2ncia:", None))
        self.label_Minimo.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Maximo.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Media.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Mediana.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_desvioPadrao.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Variancia.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_countdown_questions.setText("")
        self.btnStart.setText(QCoreApplication.translate("MainWindowUi", u"Come\u00e7ar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindowUi", u"Perguntas", None))
        self.btn_CalcularResultados.setText(QCoreApplication.translate("MainWindowUi", u"Calcular", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindowUi", u"Valores em Respouso", None))
        self.label_Minimo_PR.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Media_PR.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_34.setText(QCoreApplication.translate("MainWindowUi", u"Vari\u00e2ncia:", None))
        self.label_Variancia_PR.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Maximo_PR.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Mediana_PR.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_desvioPadrao_PR.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_33.setText(QCoreApplication.translate("MainWindowUi", u"Desvio-Padr\u00e3o:", None))
        self.label_29.setText(QCoreApplication.translate("MainWindowUi", u"M\u00ednimo:", None))
        self.label_32.setText(QCoreApplication.translate("MainWindowUi", u"Mediana:", None))
        self.label_31.setText(QCoreApplication.translate("MainWindowUi", u"M\u00e9dia (BL):", None))
        self.label_30.setText(QCoreApplication.translate("MainWindowUi", u"M\u00e1ximo:", None))
        self.btn_onePlotData.setText(QCoreApplication.translate("MainWindowUi", u"One Plot Data", None))
        self.btn_multiPlotData.setText(QCoreApplication.translate("MainWindowUi", u"Multi Plot Data", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindowUi", u"Quest\u00e3o n\u00ba 1", None))
        self.label_Media_RQ1.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_RD_RQ1.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_desvioPadrao_RQ1.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Resultado_Q1.setText(QCoreApplication.translate("MainWindowUi", u"...", None))
        self.label_46.setText(QCoreApplication.translate("MainWindowUi", u"M\u00ednimo:", None))
        self.label_65.setText(QCoreApplication.translate("MainWindowUi", u"SCR Lantency:", None))
        self.label_PA_RQ1.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Maximo_RQ1.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_60.setText(QCoreApplication.translate("MainWindowUi", u"Resultado:", None))
        self.label_41.setText(QCoreApplication.translate("MainWindowUi", u"M\u00e1ximo:", None))
        self.input_ResultadoFinal_Q1.setText(QCoreApplication.translate("MainWindowUi", u"TextLabel", None))
        self.label_Mediana_RQ1.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_44.setText(QCoreApplication.translate("MainWindowUi", u"M\u00e9dia:", None))
        self.label_Variancia_RQ1.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Minimo_RQ1.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_45.setText(QCoreApplication.translate("MainWindowUi", u"Peak Time:", None))
        self.label_PT_RQ1.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_43.setText(QCoreApplication.translate("MainWindowUi", u"Vari\u00e2ncia:", None))
        self.label_47.setText(QCoreApplication.translate("MainWindowUi", u"Mediana:", None))
        self.label_LAT_RQ1.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_63.setText(QCoreApplication.translate("MainWindowUi", u"Peak Amplitude:", None))
        self.label_64.setText(QCoreApplication.translate("MainWindowUi", u"Response Delay:", None))
        self.label_42.setText(QCoreApplication.translate("MainWindowUi", u"Desvio-Padr\u00e3o:", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindowUi", u"Quest\u00e3o n\u00ba 2", None))
        self.label_68.setText(QCoreApplication.translate("MainWindowUi", u"Peak Time:", None))
        self.label_54.setText(QCoreApplication.translate("MainWindowUi", u"Vari\u00e2ncia:", None))
        self.label_Mediana_RQ2.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.input_ResultadoFinal_Q2.setText(QCoreApplication.translate("MainWindowUi", u"TextLabel", None))
        self.label_51.setText(QCoreApplication.translate("MainWindowUi", u"Desvio-Padr\u00e3o:", None))
        self.label_PT_RQ2.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Variancia_RQ2.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_PA_RQ2.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_LAT_RQ2.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_69.setText(QCoreApplication.translate("MainWindowUi", u"Response Delay:", None))
        self.label_RD_RQ2.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Maximo_RQ2.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Minimo_RQ2.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_53.setText(QCoreApplication.translate("MainWindowUi", u"Resultado:", None))
        self.label_Media_RQ2.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_66.setText(QCoreApplication.translate("MainWindowUi", u"SCR Lantency:", None))
        self.label_67.setText(QCoreApplication.translate("MainWindowUi", u"Peak Amplitude:", None))
        self.label_52.setText(QCoreApplication.translate("MainWindowUi", u"M\u00ednimo:", None))
        self.label_Resultado_Q2.setText(QCoreApplication.translate("MainWindowUi", u"...", None))
        self.label_49.setText(QCoreApplication.translate("MainWindowUi", u"M\u00e1ximo:", None))
        self.label_50.setText(QCoreApplication.translate("MainWindowUi", u"Mediana:", None))
        self.label_desvioPadrao_RQ2.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_48.setText(QCoreApplication.translate("MainWindowUi", u"M\u00e9dia:", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindowUi", u"Quest\u00e3o n\u00ba 3", None))
        self.label_57.setText(QCoreApplication.translate("MainWindowUi", u"Mediana:", None))
        self.label_Resultado_Q3.setText(QCoreApplication.translate("MainWindowUi", u"...", None))
        self.label_desvioPadrao_RQ3.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Minimo_RQ3.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Mediana_RQ3.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_56.setText(QCoreApplication.translate("MainWindowUi", u"M\u00e1ximo:", None))
        self.label_RD_RQ3.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_59.setText(QCoreApplication.translate("MainWindowUi", u"M\u00ednimo:", None))
        self.label_55.setText(QCoreApplication.translate("MainWindowUi", u"M\u00e9dia:", None))
        self.label_Media_RQ3.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_70.setText(QCoreApplication.translate("MainWindowUi", u"SCR Lantency:", None))
        self.label_72.setText(QCoreApplication.translate("MainWindowUi", u"Peak Time:", None))
        self.label_61.setText(QCoreApplication.translate("MainWindowUi", u"Vari\u00e2ncia:", None))
        self.input_ResultadoFinal_Q3.setText(QCoreApplication.translate("MainWindowUi", u"TextLabel", None))
        self.label_62.setText(QCoreApplication.translate("MainWindowUi", u"Resultado:", None))
        self.label_71.setText(QCoreApplication.translate("MainWindowUi", u"Peak Amplitude:", None))
        self.label_PT_RQ3.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_73.setText(QCoreApplication.translate("MainWindowUi", u"Response Delay:", None))
        self.label_Maximo_RQ3.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_LAT_RQ3.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_Variancia_RQ3.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.label_58.setText(QCoreApplication.translate("MainWindowUi", u"Desvio-Padr\u00e3o:", None))
        self.label_PA_RQ3.setText(QCoreApplication.translate("MainWindowUi", u"0.00uS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindowUi", u"Resultados", None))
        self.textEdit.setHtml(QCoreApplication.translate("MainWindowUi", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Projecto desenvolvido no \u00e2mbito da unidade curricular de </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Bioinstrumenta\u00e7\u00e3o</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align"
                        "=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Realizado por:</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Elson Sim\u00f5es - a20845</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">\u00d3scar Ara\u00fajo - a20844</span></p>\n"
""
                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Rui Lopes - a21674</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindowUi", u"Sobre", None))
    # retranslateUi

