# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from cProfile import label
from PyQt5 import QtCore, QtGui, QtWidgets
import threading
from PyQt5.QtWidgets import *
from ui.PlotWindowConfig import Ui_PlotWindow
from scipy.signal import find_peaks
import matplotlib.pyplot as plt
from PyQt5.QtGui import *
from dataReader import *




class Ui_MainWindowUi(object):
    def setupUi(self, MainWindowUi):
        MainWindowUi.setObjectName("MainWindowUi")
        MainWindowUi.resize(1094, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindowUi)
        self.centralwidget.setObjectName("centralwidget")
        self.labelDetectorMentiras = QtWidgets.QLabel(self.centralwidget)
        self.labelDetectorMentiras.setGeometry(QtCore.QRect(80, 30, 921, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelDetectorMentiras.setFont(font)
        self.labelDetectorMentiras.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDetectorMentiras.setObjectName("labelDetectorMentiras")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 90, 1091, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 40, 1061, 441))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.inputPergunta = QtWidgets.QLabel(self.tab_2)
        self.inputPergunta.setGeometry(QtCore.QRect(10, 120, 1011, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputPergunta.setFont(font)
        self.inputPergunta.setAlignment(QtCore.Qt.AlignCenter)
        self.inputPergunta.setObjectName("inputPergunta")
        self.btnBitalinoConnect = QtWidgets.QPushButton(self.tab_2)
        self.btnBitalinoConnect.setGeometry(QtCore.QRect(10, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnBitalinoConnect.setFont(font)
        self.btnBitalinoConnect.setObjectName("btnBitalinoConnect")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 310, 1071, 141))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(60, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(320, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(590, 40, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(300, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(620, 90, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_Minimo = QtWidgets.QLabel(self.groupBox)
        self.label_Minimo.setGeometry(QtCore.QRect(140, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Minimo.setFont(font)
        self.label_Minimo.setObjectName("label_Minimo")
        self.label_Maximo = QtWidgets.QLabel(self.groupBox)
        self.label_Maximo.setGeometry(QtCore.QRect(140, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Maximo.setFont(font)
        self.label_Maximo.setObjectName("label_Maximo")
        self.label_Media = QtWidgets.QLabel(self.groupBox)
        self.label_Media.setGeometry(QtCore.QRect(410, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Media.setFont(font)
        self.label_Media.setObjectName("label_Media")
        self.label_Mediana = QtWidgets.QLabel(self.groupBox)
        self.label_Mediana.setGeometry(QtCore.QRect(410, 90, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Mediana.setFont(font)
        self.label_Mediana.setObjectName("label_Mediana")
        self.label_desvioPadrao = QtWidgets.QLabel(self.groupBox)
        self.label_desvioPadrao.setGeometry(QtCore.QRect(740, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_desvioPadrao.setFont(font)
        self.label_desvioPadrao.setObjectName("label_desvioPadrao")
        self.label_Variancia = QtWidgets.QLabel(self.groupBox)
        self.label_Variancia.setGeometry(QtCore.QRect(740, 90, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Variancia.setFont(font)
        self.label_Variancia.setObjectName("label_Variancia")
        self.label_countdown_questions = QtWidgets.QLabel(self.tab_2)
        self.label_countdown_questions.setGeometry(QtCore.QRect(950, 70, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_countdown_questions.setFont(font)
        self.label_countdown_questions.setText("")
        self.label_countdown_questions.setObjectName("label_countdown_questions")
        self.btnStart = QtWidgets.QPushButton(self.tab_2)
        self.btnStart.setGeometry(QtCore.QRect(180, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.btn_CalcularResultados = QtWidgets.QPushButton(self.tab_3)
        self.btn_CalcularResultados.setGeometry(QtCore.QRect(60, 30, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_CalcularResultados.setFont(font)
        self.btn_CalcularResultados.setObjectName("btn_CalcularResultados")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 10, 761, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_Minimo_PR = QtWidgets.QLabel(self.groupBox_2)
        self.label_Minimo_PR.setGeometry(QtCore.QRect(230, 20, 55, 16))
        self.label_Minimo_PR.setObjectName("label_Minimo_PR")
        self.label_Media_PR = QtWidgets.QLabel(self.groupBox_2)
        self.label_Media_PR.setGeometry(QtCore.QRect(420, 20, 55, 16))
        self.label_Media_PR.setObjectName("label_Media_PR")
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(550, 50, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_Variancia_PR = QtWidgets.QLabel(self.groupBox_2)
        self.label_Variancia_PR.setGeometry(QtCore.QRect(640, 50, 55, 16))
        self.label_Variancia_PR.setObjectName("label_Variancia_PR")
        self.label_Maximo_PR = QtWidgets.QLabel(self.groupBox_2)
        self.label_Maximo_PR.setGeometry(QtCore.QRect(230, 50, 55, 16))
        self.label_Maximo_PR.setObjectName("label_Maximo_PR")
        self.label_Mediana_PR = QtWidgets.QLabel(self.groupBox_2)
        self.label_Mediana_PR.setGeometry(QtCore.QRect(420, 50, 55, 16))
        self.label_Mediana_PR.setObjectName("label_Mediana_PR")
        self.label_desvioPadrao_PR = QtWidgets.QLabel(self.groupBox_2)
        self.label_desvioPadrao_PR.setGeometry(QtCore.QRect(640, 20, 55, 16))
        self.label_desvioPadrao_PR.setObjectName("label_desvioPadrao_PR")
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(520, 20, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(170, 20, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(340, 50, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(330, 20, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_31.setObjectName("label_31")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(170, 50, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.btn_onePlotData = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_onePlotData.setGeometry(QtCore.QRect(20, 20, 93, 28))
        self.btn_onePlotData.setObjectName("btn_onePlotData")
        self.btn_multiPlotData = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_multiPlotData.setGeometry(QtCore.QRect(20, 50, 93, 28))
        self.btn_multiPlotData.setObjectName("btn_multiPlotData")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 110, 1071, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_Media_RQ1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_Media_RQ1.setGeometry(QtCore.QRect(220, 60, 55, 16))
        self.label_Media_RQ1.setObjectName("label_Media_RQ1")
        self.label_RD_RQ1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_RD_RQ1.setGeometry(QtCore.QRect(780, 90, 55, 16))
        self.label_RD_RQ1.setObjectName("label_RD_RQ1")
        self.label_desvioPadrao_RQ1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_desvioPadrao_RQ1.setGeometry(QtCore.QRect(400, 60, 55, 16))
        self.label_desvioPadrao_RQ1.setObjectName("label_desvioPadrao_RQ1")
        self.label_Resultado_Q1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_Resultado_Q1.setGeometry(QtCore.QRect(900, 80, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Resultado_Q1.setFont(font)
        self.label_Resultado_Q1.setObjectName("label_Resultado_Q1")
        self.label_46 = QtWidgets.QLabel(self.groupBox_3)
        self.label_46.setGeometry(QtCore.QRect(20, 60, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_65 = QtWidgets.QLabel(self.groupBox_3)
        self.label_65.setGeometry(QtCore.QRect(660, 60, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_65.setObjectName("label_65")
        self.label_PA_RQ1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_PA_RQ1.setGeometry(QtCore.QRect(590, 90, 55, 16))
        self.label_PA_RQ1.setObjectName("label_PA_RQ1")
        self.label_Maximo_RQ1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_Maximo_RQ1.setGeometry(QtCore.QRect(80, 90, 55, 16))
        self.label_Maximo_RQ1.setObjectName("label_Maximo_RQ1")
        self.label_60 = QtWidgets.QLabel(self.groupBox_3)
        self.label_60.setGeometry(QtCore.QRect(900, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.label_41 = QtWidgets.QLabel(self.groupBox_3)
        self.label_41.setGeometry(QtCore.QRect(20, 90, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.input_ResultadoFinal_Q1 = QtWidgets.QLabel(self.groupBox_3)
        self.input_ResultadoFinal_Q1.setGeometry(QtCore.QRect(20, 20, 981, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.input_ResultadoFinal_Q1.setFont(font)
        self.input_ResultadoFinal_Q1.setObjectName("input_ResultadoFinal_Q1")
        self.label_Mediana_RQ1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_Mediana_RQ1.setGeometry(QtCore.QRect(220, 90, 55, 16))
        self.label_Mediana_RQ1.setObjectName("label_Mediana_RQ1")
        self.label_44 = QtWidgets.QLabel(self.groupBox_3)
        self.label_44.setGeometry(QtCore.QRect(160, 60, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_Variancia_RQ1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_Variancia_RQ1.setGeometry(QtCore.QRect(400, 90, 55, 16))
        self.label_Variancia_RQ1.setObjectName("label_Variancia_RQ1")
        self.label_Minimo_RQ1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_Minimo_RQ1.setGeometry(QtCore.QRect(80, 60, 55, 16))
        self.label_Minimo_RQ1.setObjectName("label_Minimo_RQ1")
        self.label_45 = QtWidgets.QLabel(self.groupBox_3)
        self.label_45.setGeometry(QtCore.QRect(500, 60, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_45.setObjectName("label_45")
        self.label_PT_RQ1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_PT_RQ1.setGeometry(QtCore.QRect(590, 60, 55, 16))
        self.label_PT_RQ1.setObjectName("label_PT_RQ1")
        self.label_43 = QtWidgets.QLabel(self.groupBox_3)
        self.label_43.setGeometry(QtCore.QRect(320, 90, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_47 = QtWidgets.QLabel(self.groupBox_3)
        self.label_47.setGeometry(QtCore.QRect(150, 90, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_LAT_RQ1 = QtWidgets.QLabel(self.groupBox_3)
        self.label_LAT_RQ1.setGeometry(QtCore.QRect(780, 60, 55, 16))
        self.label_LAT_RQ1.setObjectName("label_LAT_RQ1")
        self.label_63 = QtWidgets.QLabel(self.groupBox_3)
        self.label_63.setGeometry(QtCore.QRect(480, 90, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_3)
        self.label_64.setGeometry(QtCore.QRect(660, 90, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_64.setObjectName("label_64")
        self.label_42 = QtWidgets.QLabel(self.groupBox_3)
        self.label_42.setGeometry(QtCore.QRect(290, 60, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 240, 1071, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_68 = QtWidgets.QLabel(self.groupBox_4)
        self.label_68.setGeometry(QtCore.QRect(500, 60, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_68.setObjectName("label_68")
        self.label_54 = QtWidgets.QLabel(self.groupBox_4)
        self.label_54.setGeometry(QtCore.QRect(320, 90, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_Mediana_RQ2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Mediana_RQ2.setGeometry(QtCore.QRect(220, 90, 55, 16))
        self.label_Mediana_RQ2.setObjectName("label_Mediana_RQ2")
        self.input_ResultadoFinal_Q2 = QtWidgets.QLabel(self.groupBox_4)
        self.input_ResultadoFinal_Q2.setGeometry(QtCore.QRect(20, 20, 981, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.input_ResultadoFinal_Q2.setFont(font)
        self.input_ResultadoFinal_Q2.setObjectName("input_ResultadoFinal_Q2")
        self.label_51 = QtWidgets.QLabel(self.groupBox_4)
        self.label_51.setGeometry(QtCore.QRect(290, 60, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_PT_RQ2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_PT_RQ2.setGeometry(QtCore.QRect(590, 60, 55, 16))
        self.label_PT_RQ2.setObjectName("label_PT_RQ2")
        self.label_Variancia_RQ2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Variancia_RQ2.setGeometry(QtCore.QRect(400, 90, 55, 16))
        self.label_Variancia_RQ2.setObjectName("label_Variancia_RQ2")
        self.label_PA_RQ2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_PA_RQ2.setGeometry(QtCore.QRect(590, 90, 55, 16))
        self.label_PA_RQ2.setObjectName("label_PA_RQ2")
        self.label_LAT_RQ2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_LAT_RQ2.setGeometry(QtCore.QRect(780, 60, 55, 16))
        self.label_LAT_RQ2.setObjectName("label_LAT_RQ2")
        self.label_69 = QtWidgets.QLabel(self.groupBox_4)
        self.label_69.setGeometry(QtCore.QRect(660, 90, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_69.setObjectName("label_69")
        self.label_RD_RQ2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_RD_RQ2.setGeometry(QtCore.QRect(780, 90, 55, 16))
        self.label_RD_RQ2.setObjectName("label_RD_RQ2")
        self.label_Maximo_RQ2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Maximo_RQ2.setGeometry(QtCore.QRect(80, 90, 55, 16))
        self.label_Maximo_RQ2.setObjectName("label_Maximo_RQ2")
        self.label_Minimo_RQ2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Minimo_RQ2.setGeometry(QtCore.QRect(80, 60, 55, 16))
        self.label_Minimo_RQ2.setObjectName("label_Minimo_RQ2")
        self.label_53 = QtWidgets.QLabel(self.groupBox_4)
        self.label_53.setGeometry(QtCore.QRect(900, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_Media_RQ2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Media_RQ2.setGeometry(QtCore.QRect(220, 60, 55, 16))
        self.label_Media_RQ2.setObjectName("label_Media_RQ2")
        self.label_66 = QtWidgets.QLabel(self.groupBox_4)
        self.label_66.setGeometry(QtCore.QRect(660, 60, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.groupBox_4)
        self.label_67.setGeometry(QtCore.QRect(480, 90, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_67.setObjectName("label_67")
        self.label_52 = QtWidgets.QLabel(self.groupBox_4)
        self.label_52.setGeometry(QtCore.QRect(20, 60, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_Resultado_Q2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Resultado_Q2.setGeometry(QtCore.QRect(900, 80, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Resultado_Q2.setFont(font)
        self.label_Resultado_Q2.setObjectName("label_Resultado_Q2")
        self.label_49 = QtWidgets.QLabel(self.groupBox_4)
        self.label_49.setGeometry(QtCore.QRect(20, 90, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.groupBox_4)
        self.label_50.setGeometry(QtCore.QRect(150, 90, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_desvioPadrao_RQ2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_desvioPadrao_RQ2.setGeometry(QtCore.QRect(400, 60, 55, 16))
        self.label_desvioPadrao_RQ2.setObjectName("label_desvioPadrao_RQ2")
        self.label_48 = QtWidgets.QLabel(self.groupBox_4)
        self.label_48.setGeometry(QtCore.QRect(160, 60, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 370, 1071, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_57 = QtWidgets.QLabel(self.groupBox_5)
        self.label_57.setGeometry(QtCore.QRect(150, 90, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.label_Resultado_Q3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_Resultado_Q3.setGeometry(QtCore.QRect(900, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Resultado_Q3.setFont(font)
        self.label_Resultado_Q3.setObjectName("label_Resultado_Q3")
        self.label_desvioPadrao_RQ3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_desvioPadrao_RQ3.setGeometry(QtCore.QRect(400, 60, 55, 16))
        self.label_desvioPadrao_RQ3.setObjectName("label_desvioPadrao_RQ3")
        self.label_Minimo_RQ3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_Minimo_RQ3.setGeometry(QtCore.QRect(80, 60, 55, 16))
        self.label_Minimo_RQ3.setObjectName("label_Minimo_RQ3")
        self.label_Mediana_RQ3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_Mediana_RQ3.setGeometry(QtCore.QRect(220, 90, 55, 16))
        self.label_Mediana_RQ3.setObjectName("label_Mediana_RQ3")
        self.label_56 = QtWidgets.QLabel(self.groupBox_5)
        self.label_56.setGeometry(QtCore.QRect(20, 90, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_RD_RQ3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_RD_RQ3.setGeometry(QtCore.QRect(780, 90, 55, 16))
        self.label_RD_RQ3.setObjectName("label_RD_RQ3")
        self.label_59 = QtWidgets.QLabel(self.groupBox_5)
        self.label_59.setGeometry(QtCore.QRect(20, 60, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.label_55 = QtWidgets.QLabel(self.groupBox_5)
        self.label_55.setGeometry(QtCore.QRect(160, 60, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_Media_RQ3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_Media_RQ3.setGeometry(QtCore.QRect(220, 60, 55, 16))
        self.label_Media_RQ3.setObjectName("label_Media_RQ3")
        self.label_70 = QtWidgets.QLabel(self.groupBox_5)
        self.label_70.setGeometry(QtCore.QRect(670, 60, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_70.setObjectName("label_70")
        self.label_72 = QtWidgets.QLabel(self.groupBox_5)
        self.label_72.setGeometry(QtCore.QRect(500, 60, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_72.setObjectName("label_72")
        self.label_61 = QtWidgets.QLabel(self.groupBox_5)
        self.label_61.setGeometry(QtCore.QRect(320, 90, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.input_ResultadoFinal_Q3 = QtWidgets.QLabel(self.groupBox_5)
        self.input_ResultadoFinal_Q3.setGeometry(QtCore.QRect(20, 20, 981, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.input_ResultadoFinal_Q3.setFont(font)
        self.input_ResultadoFinal_Q3.setObjectName("input_ResultadoFinal_Q3")
        self.label_62 = QtWidgets.QLabel(self.groupBox_5)
        self.label_62.setGeometry(QtCore.QRect(900, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.label_71 = QtWidgets.QLabel(self.groupBox_5)
        self.label_71.setGeometry(QtCore.QRect(480, 90, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_71.setObjectName("label_71")
        self.label_PT_RQ3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_PT_RQ3.setGeometry(QtCore.QRect(590, 60, 55, 16))
        self.label_PT_RQ3.setObjectName("label_PT_RQ3")
        self.label_73 = QtWidgets.QLabel(self.groupBox_5)
        self.label_73.setGeometry(QtCore.QRect(660, 90, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_73.setObjectName("label_73")
        self.label_Maximo_RQ3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_Maximo_RQ3.setGeometry(QtCore.QRect(80, 90, 55, 16))
        self.label_Maximo_RQ3.setObjectName("label_Maximo_RQ3")
        self.label_LAT_RQ3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_LAT_RQ3.setGeometry(QtCore.QRect(780, 60, 55, 16))
        self.label_LAT_RQ3.setObjectName("label_LAT_RQ3")
        self.label_Variancia_RQ3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_Variancia_RQ3.setGeometry(QtCore.QRect(400, 90, 55, 16))
        self.label_Variancia_RQ3.setObjectName("label_Variancia_RQ3")
        self.label_58 = QtWidgets.QLabel(self.groupBox_5)
        self.label_58.setGeometry(QtCore.QRect(290, 60, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_PA_RQ3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_PA_RQ3.setGeometry(QtCore.QRect(590, 90, 55, 16))
        self.label_PA_RQ3.setObjectName("label_PA_RQ3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit.setGeometry(QtCore.QRect(80, 90, 871, 291))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindowUi.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowUi)
        self.statusbar.setObjectName("statusbar")
        MainWindowUi.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowUi)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowUi)

    def retranslateUi(self, MainWindowUi):
        _translate = QtCore.QCoreApplication.translate
        MainWindowUi.setWindowTitle(_translate("MainWindowUi", "Detector de Mentiras"))
        self.labelDetectorMentiras.setText(_translate("MainWindowUi", "Detector de Mentiras"))
        self.textEdit_2.setHtml(_translate("MainWindowUi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Instruções para o teste:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1. Coloque os elétrodos na palma da mão</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2. Respire normalmente e tente abstrair-se do que lhe rodeia</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3. Serão usados 15seg antes de iniciar o teste, para fazer criar um padrão da sua resposta galvánica.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">4. Depois serão apresentadas 3 perguntas ao qual terá 15 segundos para responder a cada uma</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">5. Após o final das perguntas será apresentado os resultado do teste</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindowUi", "Introdução"))
        self.inputPergunta.setText(_translate("MainWindowUi", "Perguntas..."))
        self.btnBitalinoConnect.setText(_translate("MainWindowUi", "Conectar Bitalino"))
        self.groupBox.setTitle(_translate("MainWindowUi", "Dados em tempo real"))
        self.label.setText(_translate("MainWindowUi", "Mínimo:"))
        self.label_2.setText(_translate("MainWindowUi", "Máximo:"))
        self.label_3.setText(_translate("MainWindowUi", "Média:"))
        self.label_4.setText(_translate("MainWindowUi", "Desvio-Padrão:"))
        self.label_5.setText(_translate("MainWindowUi", "Mediana:"))
        self.label_6.setText(_translate("MainWindowUi", "Variância:"))
        self.label_Minimo.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Maximo.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Media.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Mediana.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_desvioPadrao.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Variancia.setText(_translate("MainWindowUi", "0.00uS"))
        self.btnStart.setText(_translate("MainWindowUi", "Começar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindowUi", "Perguntas"))
        self.btn_CalcularResultados.setText(_translate("MainWindowUi", "Calcular"))
        self.groupBox_2.setTitle(_translate("MainWindowUi", "Valores em Respouso"))
        self.label_Minimo_PR.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Media_PR.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_34.setText(_translate("MainWindowUi", "Variância:"))
        self.label_Variancia_PR.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Maximo_PR.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Mediana_PR.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_desvioPadrao_PR.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_33.setText(_translate("MainWindowUi", "Desvio-Padrão:"))
        self.label_29.setText(_translate("MainWindowUi", "Mínimo:"))
        self.label_32.setText(_translate("MainWindowUi", "Mediana:"))
        self.label_31.setText(_translate("MainWindowUi", "Média (BL):"))
        self.label_30.setText(_translate("MainWindowUi", "Máximo:"))
        self.btn_onePlotData.setText(_translate("MainWindowUi", "One Plot Data"))
        self.btn_multiPlotData.setText(_translate("MainWindowUi", "Multi Plot Data"))
        self.groupBox_3.setTitle(_translate("MainWindowUi", "Questão nº 1"))
        self.label_Media_RQ1.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_RD_RQ1.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_desvioPadrao_RQ1.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Resultado_Q1.setText(_translate("MainWindowUi", "..."))
        self.label_46.setText(_translate("MainWindowUi", "Mínimo:"))
        self.label_65.setText(_translate("MainWindowUi", "SCR Lantency:"))
        self.label_PA_RQ1.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Maximo_RQ1.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_60.setText(_translate("MainWindowUi", "Resultado:"))
        self.label_41.setText(_translate("MainWindowUi", "Máximo:"))
        self.input_ResultadoFinal_Q1.setText(_translate("MainWindowUi", "TextLabel"))
        self.label_Mediana_RQ1.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_44.setText(_translate("MainWindowUi", "Média:"))
        self.label_Variancia_RQ1.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Minimo_RQ1.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_45.setText(_translate("MainWindowUi", "Peak Time:"))
        self.label_PT_RQ1.setText(_translate("MainWindowUi", "0.00seg"))
        self.label_43.setText(_translate("MainWindowUi", "Variância:"))
        self.label_47.setText(_translate("MainWindowUi", "Mediana:"))
        self.label_LAT_RQ1.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_63.setText(_translate("MainWindowUi", "Peak Amplitude:"))
        self.label_64.setText(_translate("MainWindowUi", "Response Delay:"))
        self.label_42.setText(_translate("MainWindowUi", "Desvio-Padrão:"))
        self.groupBox_4.setTitle(_translate("MainWindowUi", "Questão nº 2"))
        self.label_68.setText(_translate("MainWindowUi", "Peak Time:"))
        self.label_54.setText(_translate("MainWindowUi", "Variância:"))
        self.label_Mediana_RQ2.setText(_translate("MainWindowUi", "0.00uS"))
        self.input_ResultadoFinal_Q2.setText(_translate("MainWindowUi", "TextLabel"))
        self.label_51.setText(_translate("MainWindowUi", "Desvio-Padrão:"))
        self.label_PT_RQ2.setText(_translate("MainWindowUi", "0.00seg"))
        self.label_Variancia_RQ2.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_PA_RQ2.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_LAT_RQ2.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_69.setText(_translate("MainWindowUi", "Response Delay:"))
        self.label_RD_RQ2.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Maximo_RQ2.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Minimo_RQ2.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_53.setText(_translate("MainWindowUi", "Resultado:"))
        self.label_Media_RQ2.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_66.setText(_translate("MainWindowUi", "SCR Lantency:"))
        self.label_67.setText(_translate("MainWindowUi", "Peak Amplitude:"))
        self.label_52.setText(_translate("MainWindowUi", "Mínimo:"))
        self.label_Resultado_Q2.setText(_translate("MainWindowUi", "..."))
        self.label_49.setText(_translate("MainWindowUi", "Máximo:"))
        self.label_50.setText(_translate("MainWindowUi", "Mediana:"))
        self.label_desvioPadrao_RQ2.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_48.setText(_translate("MainWindowUi", "Média:"))
        self.groupBox_5.setTitle(_translate("MainWindowUi", "Questão nº 3"))
        self.label_57.setText(_translate("MainWindowUi", "Mediana:"))
        self.label_Resultado_Q3.setText(_translate("MainWindowUi", "..."))
        self.label_desvioPadrao_RQ3.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Minimo_RQ3.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Mediana_RQ3.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_56.setText(_translate("MainWindowUi", "Máximo:"))
        self.label_RD_RQ3.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_59.setText(_translate("MainWindowUi", "Mínimo:"))
        self.label_55.setText(_translate("MainWindowUi", "Média:"))
        self.label_Media_RQ3.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_70.setText(_translate("MainWindowUi", "SCR Lantency:"))
        self.label_72.setText(_translate("MainWindowUi", "Peak Time:"))
        self.label_61.setText(_translate("MainWindowUi", "Variância:"))
        self.input_ResultadoFinal_Q3.setText(_translate("MainWindowUi", "TextLabel"))
        self.label_62.setText(_translate("MainWindowUi", "Resultado:"))
        self.label_71.setText(_translate("MainWindowUi", "Peak Amplitude:"))
        self.label_PT_RQ3.setText(_translate("MainWindowUi", "0.00seg"))
        self.label_73.setText(_translate("MainWindowUi", "Response Delay:"))
        self.label_Maximo_RQ3.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_LAT_RQ3.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_Variancia_RQ3.setText(_translate("MainWindowUi", "0.00uS"))
        self.label_58.setText(_translate("MainWindowUi", "Desvio-Padrão:"))
        self.label_PA_RQ3.setText(_translate("MainWindowUi", "0.00uS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindowUi", "Resultados"))
        self.textEdit.setHtml(_translate("MainWindowUi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Projecto desenvolvido no âmbito da unidade curricular de </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Bioinstrumentação</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Realizado por:</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Elson Simões - a20845</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Óscar Araújo - a20844</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Rui Lopes - a21674</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindowUi", "Sobre"))


        
        
        
        
        
        
        
        
        
        
        
        
        ################### Start working DATA ####################
        
        
        
        
        self.liveData = [] #Recebe os dados em tempo real
        self.accumulatedData = [] #Recebe e acumula os dados
        self.restArray = []
        self.question1Array = []
        self.question2Array = []
        self.question3Array = []
        
        
        #definição das questões
        self.questions = [
            "Garante à máquina da verdade que não copiou no teste de Bioinstrumentação?",
            "Garante à máquina da verdade que nunca copiou num teste das UC's do professor Nuno Dias?",
            "Garante à máquina da verdade que nunca falou mal do professor Nuno Dias?",
            ""
        ]
        
        self.timeToRest = 15
        self.timeToQuestion = 15
        self.countdown = [self.timeToRest, self.timeToQuestion]

        self.countdownTimer = QtCore.QTimer()
        self.btnBitalinoConnect.clicked.connect(lambda:self.startBitalinoPlotting())
        self.btnStart.setEnabled(False)
        self.btnStart.clicked.connect(lambda:self.start_timer("restCountDown"))
        
        self.arrayIndex = 0        
        
        self.btn_CalcularResultados.setEnabled(False)
        self.btn_CalcularResultados.clicked.connect(lambda:self.resultsCalc())
        self.btn_onePlotData.setEnabled(False)
        self.btn_multiPlotData.setEnabled(False)
        self.btn_onePlotData.clicked.connect(lambda:self.onePlotData())
        self.btn_multiPlotData.clicked.connect(lambda:self.multiPlotData())    

    
    def startBitalinoPlotting(self):
        self.btnBitalinoConnect.setEnabled(False)
        self.btnStart.setEnabled(True)
        plotWin = Ui_PlotWindow()
        self.stop_threads = False
        # Add the callbackfunc to ..
        self.myDataLoop = threading.Thread(name = 'myDataLoop', target = dataSendLoop, daemon = True, args = (plotWin.addData_callbackFunc, self.calcResults_callbackFunc))
        self.myDataLoop.start()
        return
    
    
    def calcResults_callbackFunc(self, usData):
        self.liveData = usData
        
        if(self.arrayIndex == 0):
            self.restArray.append(usData)
        elif(self.arrayIndex == 1):
            self.question1Array.append(usData)
        elif(self.arrayIndex == 2):
            self.question2Array.append(usData)
        elif(self.arrayIndex == 3):
            self.question3Array.append(usData)
        
        
        self.accumulatedData.append(usData)
        #print(self.dataArray)
        self.minimo = format(np.min(self.accumulatedData), '.2f')
        self.maximo = format(np.max(self.accumulatedData), '.2f')
        self.media = format(np.mean(self.accumulatedData), '.2f')
        self.mediana = format(np.median(self.accumulatedData), '.2f')
        self.desvioPadrao = format(np.std(self.accumulatedData), '.2f')
        self.variancia = format(np.var(self.accumulatedData), '.2f')
        
        #self.picos = find_peaks(self.accumulatedData, height = 1, threshold = 1, distance = 1)
        #print('picos: ', self.picos)
        
        #print('Maximo', self.maximo)
        
        self.label_Minimo.setText(str(self.minimo)+'uS')
        self.label_Maximo.setText(str(self.maximo)+'uS')
        self.label_Media.setText(str(self.media)+'uS')
        self.label_Mediana.setText(str(self.mediana)+'uS')
        self.label_desvioPadrao.setText(str(self.desvioPadrao)+'uS')
        self.label_Variancia.setText(str(self.variancia)+'uS')
        

        
    
    def start_timer(self, funcao):
        
        if(funcao == "restCountDown"):
            self.inputPergunta.setText("Respire fundo e concentre-se...")
            self.countdownTimer.timeout.connect(self.restCountDown)
            self.countdownTimer.start(1000) # fires every 1000ms = 1s

        elif (funcao == "questionsCountDown"):
            self.countdownTimer.timeout.connect(self.questionsCountDown)
            self.countdownTimer.start(1000) # fires every 1000ms = 1s
        
            



    def restCountDown(self):
        self.btnStart.setEnabled(False)
        if (self.countdown[0] <= 0):
            self.countdownTimer.stop()
            self.countdownTimer.timeout.disconnect()
            self.countdown[0] = 0
            self.arrayIndex += 1
            self.start_timer("questionsCountDown")
            
        
        #update a clock label that shows the countdown value
        self.inputPergunta.setText(str(self.countdown[0]))
        self.countdown[0] -= 1
        
        
    
    
    def questionsCountDown(self):
        self.qtdQuestions = len(self.questions)

        if((self.arrayIndex) >= self.qtdQuestions):
            self.btn_CalcularResultados.setEnabled(True)
            self.inputPergunta.setText("O seu teste terminou, aguarde os resultados!")
            self.label_countdown_questions.setText("")
            self.countdownTimer.stop()
            self.countdownTimer.timeout.disconnect()
        else:
            if (self.countdown[1] <= 0):
                self.countdownTimer.stop()
                self.countdownTimer.timeout.disconnect()
                self.countdown[1] = self.timeToQuestion
                self.arrayIndex += 1
                self.start_timer("questionsCountDown")
                

            self.inputPergunta.setText(self.questions[self.arrayIndex-1])
            self.label_countdown_questions.setText(str(self.countdown[1]))
            self.countdown[1] -= 1
        




        
    def resultsCalc(self):
        self.btn_onePlotData.setEnabled(True)
        self.btn_multiPlotData.setEnabled(True)
        self.input_ResultadoFinal_Q1.setText(str(self.questions[0]))
        self.input_ResultadoFinal_Q2.setText(str(self.questions[1]))
        self.input_ResultadoFinal_Q3.setText(str(self.questions[2]))
        
        #Calculo dos dados do periodo de repouso (PR)
        #print("#Calculo dos dados do periodo de repouso (PR) ",self.restArray)
        self.minimoPR = format(np.min(self.restArray), '.2f')
        self.maximoPR = format(np.max(self.restArray), '.2f')
        self.mediaPR = format(np.mean(self.restArray), '.2f')
        self.medianaPR = format(np.median(self.restArray), '.2f')
        self.desvioPadraoPR = format(np.std(self.restArray), '.2f')
        self.varianciaPR = format(np.var(self.restArray), '.2f')
                
        self.label_Maximo_PR.setText(str(self.maximoPR) + 'uS')
        self.label_Minimo_PR.setText(str(self.minimoPR) + 'uS')
        self.label_Media_PR.setText(str(self.mediaPR) + 'uS')
        self.label_Mediana_PR.setText(str(self.medianaPR) + 'uS')
        self.label_desvioPadrao_PR.setText(str(self.desvioPadraoPR) + 'uS')
        self.label_Variancia_PR.setText(str(self.varianciaPR) + 'uS')

    
        #valores limite para decidir o teste
        self.meanFivePercent = format(np.mean(self.restArray)*1.05, '.2f')

    
        #Calculo dos dados do periodo de 1ª Questao (PR)
        #print("#Calculo dos dados do periodo de 1ª Questao (PR) ",self.question1Array)
        self.minimoQ1 = format(np.min(self.question1Array), '.2f')
        self.maximoQ1 = format(np.max(self.question1Array), '.2f')
        self.mediaQ1 = format(np.mean(self.question1Array), '.2f')
        self.medianaQ1 = format(np.median(self.question1Array), '.2f')
        self.desvioPadraoQ1 = format(np.std(self.question1Array), '.2f')
        self.varianciaQ1 = format(np.var(self.question1Array), '.2f')
                
        self.label_Maximo_RQ1.setText(str(self.maximoQ1) + 'uS')
        self.label_Minimo_RQ1.setText(str(self.minimoQ1) + 'uS')
        self.label_Media_RQ1.setText(str(self.mediaQ1) + 'uS')
        self.label_Mediana_RQ1.setText(str(self.medianaQ1) + 'uS')
        self.label_desvioPadrao_RQ1.setText(str(self.desvioPadraoQ1) + 'uS')
        self.label_Variancia_RQ1.setText(str(self.varianciaQ1) + 'uS')
        
        
        
        if(self.mediaQ1 > self.meanFivePercent):
            self.label_Resultado_Q1.setText("Você mentiu")
        elif(self.mediaQ1 < self.mediaPR):
            self.label_Resultado_Q1.setText("Você disse a verdade")
        else:
            self.label_Resultado_Q1.setText("A máquina está indecisa")
        
    
        #Calculo dos dados do periodo de 2ª Questao (PR)
        #print("#Calculo dos dados do periodo de 2ª Questao (PR) ",self.question2Array)
        self.minimoQ2 = format(np.min(self.question2Array), '.2f')
        self.maximoQ2 = format(np.max(self.question2Array), '.2f')
        self.mediaQ2 = format(np.mean(self.question2Array), '.2f')
        self.medianaQ2 = format(np.median(self.question2Array), '.2f')
        self.desvioPadraoQ2 = format(np.std(self.question2Array), '.2f')
        self.varianciaQ2 = format(np.var(self.question2Array), '.2f')
                
        self.label_Maximo_RQ2.setText(str(self.maximoQ2) + 'uS')
        self.label_Minimo_RQ2.setText(str(self.minimoQ2) + 'uS')
        self.label_Media_RQ2.setText(str(self.mediaQ2) + 'uS')
        self.label_Mediana_RQ2.setText(str(self.medianaQ2) + 'uS')
        self.label_desvioPadrao_RQ2.setText(str(self.desvioPadraoQ2) + 'uS')
        self.label_Variancia_RQ2.setText(str(self.varianciaQ2) + 'uS')
        
        if(self.mediaQ2 > self.meanFivePercent):
            self.label_Resultado_Q2.setText("Você mentiu")
        elif(self.mediaQ2 < self.mediaPR):
            self.label_Resultado_Q2.setText("Você disse a verdade")
        else:
            self.label_Resultado_Q2.setText("A máquina está indecisa")
        
        
        
        #Calculo dos dados do periodo de 3ª Questao (PR)
        #print("#Calculo dos dados do periodo de 3ª Questao (PR) ",self.question3Array)
        self.minimoQ3 = format(np.min(self.question3Array), '.2f')
        self.maximoQ3 = format(np.max(self.question3Array), '.2f')
        self.mediaQ3 = format(np.mean(self.question3Array), '.2f')
        self.medianaQ3 = format(np.median(self.question3Array), '.2f')
        self.desvioPadraoQ3 = format(np.std(self.question3Array), '.2f')
        self.varianciaQ3 = format(np.var(self.question3Array), '.2f')
                
        self.label_Maximo_RQ3.setText(str(self.maximoQ3) + 'uS')
        self.label_Minimo_RQ3.setText(str(self.minimoQ3) + 'uS')
        self.label_Media_RQ3.setText(str(self.mediaQ3) + 'uS')
        self.label_Mediana_RQ3.setText(str(self.medianaQ3) + 'uS')
        self.label_desvioPadrao_RQ3.setText(str(self.desvioPadraoQ3) + 'uS')
        self.label_Variancia_RQ3.setText(str(self.varianciaQ3) + 'uS')
    

        if(self.mediaQ3 > self.meanFivePercent):
            self.label_Resultado_Q3.setText("Você mentiu")
        elif(self.mediaQ3 < self.mediaPR):
            self.label_Resultado_Q3.setText("Você disse a verdade")
        else:
            self.label_Resultado_Q3.setText("A máquina está indecisa")

        
        self.calcPeaks()
    
    
    
    
    def calcPeaks(self):
        
        #--------------Preparação de dados para plot do periodo de repouso ----------------
        self.yRep = np.array(self.restArray)
        self.xAxisIntervalRep = (self.timeToRest/len(self.yRep))
        self.xAxisRep = np.arange(0, self.timeToRest, self.xAxisIntervalRep) #tempo em segundos da duração do reste repouso


        #---------------Peaks da Questão 1-----------------
        self.yQ1 = np.array(self.question1Array)
        self.peaksQ1, _ = find_peaks(self.yQ1, height = 0.5)
    
        #Deteção dos picos minimos e filtro pelos que estão ao lado dos picos maximos
        self.minsQ1, _ =find_peaks(self.yQ1*-1)
        self.closest_minsQ1 = [self.minsQ1[np.argmin(np.abs(x - self.minsQ1))] for x in self.peaksQ1]    
        
        #Definição da escala do eixo X
        self.xAxisIntervalQ1 = (self.timeToQuestion/len(self.yQ1))
        self.xAxisQ1 = np.arange(0, self.timeToQuestion, self.xAxisIntervalQ1) 
        
        #Coodenadas dos picos
        self.coordXYQ1 = [(i,j) for i, j in zip(self.xAxisQ1[self.peaksQ1], self.yQ1[self.peaksQ1] )]
        
        #Coodenadas dos Closest Valleys
        self.coordXYValleyQ1 = [(i,j) for i, j in zip(self.xAxisQ1[self.minsQ1], self.yQ1[self.minsQ1] )]

        
        #Preenchimento do formulário
        self.PeakAmplitudeQ1 = format(self.coordXYQ1[0][1], '.2f')
        self.PeakTimeQ1 = format(self.coordXYQ1[0][0], '.2f')
        self.ScrLatencyQ1 = format(self.coordXYValleyQ1[0][0], '.2f')
        self.ResponseDelayQ1 =  format(float(self.PeakTimeQ1) - float(self.ScrLatencyQ1), '.2f')
        
        self.label_PT_RQ1.setText(str(self.PeakTimeQ1) + 'seg')
        self.label_PA_RQ1.setText(str(self.PeakAmplitudeQ1) + 'uS')
        self.label_LAT_RQ1.setText(str(self.ScrLatencyQ1) + 'seg')
        self.label_RD_RQ1.setText(str(self.ResponseDelayQ1) + 'seg')
    
    
    
        #---------------Peaks da Questão 2-----------------
        self.yQ2 = np.array(self.question2Array)
        self.peaksQ2, _ = find_peaks(self.yQ2, height = 0.5)
        
        #Deteção dos picos minimos e filtro pelos que estão ao lado dos picos maximos
        self.minsQ2, _ = find_peaks(self.yQ2*-1)
        self.closest_minsQ2 = [self.minsQ2[np.argmin(np.abs(x - self.minsQ2))] for x in self.peaksQ2]
        
        #Definição da escala do eixo X
        self.xAxisIntervalQ2 = (self.timeToQuestion/len(self.yQ2))
        self.xAxisQ2 = np.arange(0, self.timeToQuestion, self.xAxisIntervalQ2) 

        #Coodenadas dos picos
        self.coordXYQ2 = [(i,j) for i, j in zip(self.xAxisQ2[self.peaksQ2], self.yQ2[self.peaksQ2] )]
        
        #Coodenadas dos Closest Valleys
        self.coordXYValleyQ2 = [(i,j) for i, j in zip(self.xAxisQ2[self.minsQ2], self.yQ2[self.minsQ2] )]
        
        
        #Preenchimento do formulário
        self.PeakTimeQ2 = format(self.coordXYQ2[0][0], '.2f')
        self.PeakAmplitudeQ2 = format(self.coordXYQ2[0][1], '.2f')
        self.ScrLatencyQ2 = format(self.coordXYValleyQ2[0][0], '.2f')
        self.ResponseDelayQ2 =  format(float(self.PeakTimeQ2) - float(self.ScrLatencyQ2), '.2f')
        
        self.label_PT_RQ2.setText(str(self.PeakTimeQ2) + 'seg')
        self.label_PA_RQ2.setText(str(self.PeakAmplitudeQ2) + 'uS')
        self.label_LAT_RQ2.setText(str(self.ScrLatencyQ2) + 'seg')
        self.label_RD_RQ2.setText(str(self.ResponseDelayQ2) + 'seg')
    


        #---------------Peaks da Questão 3-----------------
        self.yQ3 = np.array(self.question3Array)
        self.peaksQ3, _ = find_peaks(self.yQ3, height = 0.5)
        
        #Deteção dos picos minimos e filtro pelos que estão ao lado dos picos maximos
        self.minsQ3, _ =find_peaks(self.yQ3*-1)
        self.closest_minsQ3 = [self.minsQ3[np.argmin(np.abs(x - self.minsQ3))] for x in self.peaksQ3]
        
        #Definição da escala do eixo X
        self.xAxisIntervalQ3 = (self.timeToQuestion/len(self.yQ3))
        self.xAxisQ3 = np.arange(0, self.timeToQuestion, self.xAxisIntervalQ3) 
        
        #Coodenadas dos picos
        self.coordXYQ3 = [(i,j) for i, j in zip(self.xAxisQ3[self.peaksQ3], self.yQ3[self.peaksQ3] )]
        
        #Coodenadas dos Closest Valleys
        self.coordXYValleyQ3 = [(i,j) for i, j in zip(self.xAxisQ3[self.minsQ3], self.yQ3[self.minsQ3] )]
        
        
        #Preenchimento do formulário usando o primeiro pico como referencia
        self.PeakTimeQ3 = format(self.coordXYQ3[0][0], '.2f')
        self.PeakAmplitudeQ3 = format(self.coordXYQ3[0][1], '.2f')
        self.ScrLatencyQ3 = format(self.coordXYValleyQ3[0][0], '.2f')
        self.ResponseDelayQ3 = format(float(self.PeakTimeQ3) - float(self.ScrLatencyQ3), '.2f')
        
        self.label_PT_RQ3.setText(str(self.PeakTimeQ3) + 'seg')
        self.label_PA_RQ3.setText(str(self.PeakAmplitudeQ3) + 'uS')
        self.label_LAT_RQ3.setText(str(self.ScrLatencyQ3) + 'seg')
        self.label_RD_RQ3.setText(str(self.ResponseDelayQ3) + 'seg')
        
        
    
        #---------------Peaks do Periodo Total do Teste-----------------
        self.yTotal = np.concatenate((self.yRep, self.yQ1, self.yQ2, self.yQ3))
        self.peaksTotal, _ = find_peaks(self.yTotal, height = 0.5)
        
        #Deteção dos picos minimos e filtro pelos que estão ao lado dos picos maximos
        self.minsTotal, _ =find_peaks(self.yTotal*-1)
        self.closest_minsTotal = [self.minsTotal[np.argmin(np.abs(x - self.minsTotal))] for x in self.peaksTotal]
        
        #Definição da escala do eixo X
        self.tempoTotal = self.timeToRest + self.timeToQuestion*(len(self.questions)-1)
        self.xAxisIntervalTotal = (self.tempoTotal/len(self.yTotal))
        self.xAxisTotal = np.arange(0, self.tempoTotal, self.xAxisIntervalTotal) #tempo em segundos da duração do reste repouso
    
        #Coodenadas dos picos
        self.coordXYTotal = [(i,j) for i, j in zip(self.xAxisTotal[self.peaksTotal], self.yTotal[self.peaksTotal] )]
    
        #Coodenadas dos Closest Valleys
        self.coordXYValleyTotal = [(i,j) for i, j in zip(self.xAxisTotal[self.minsTotal], self.yTotal[self.minsTotal] )]
        print("Coodenadas dos Valleys Proximos Total: ", self.coordXYValleyTotal)
        
        
    
    def multiPlotData(self):
        
        fig, axis = plt.subplots(2, 2)
        
        #---------------Plot Data Periodo de Repouso---------------
        
        axis[0, 0].set_title('Periodo de Repouso')
        axis[0, 0].set_ylabel('EDA (uS)')
        axis[0, 0].plot(self.xAxisRep, self.yRep)
        axis[0, 0].grid()

        
        
        #---------------Plot Data da Questão 1---------------
        axis[0, 1].set_title('Periodo da Questão nº 1')
        axis[0, 1].plot(self.xAxisQ1, self.yQ1, 'tab:orange')
        axis[0, 1].plot(self.xAxisQ1[self.peaksQ1], self.yQ1[self.peaksQ1], "x")
        axis[0, 1].plot(self.xAxisQ1[self.peaksQ1], self.yQ1[self.peaksQ1], "x")
        
        axis[0, 1].vlines(x=self.coordXYQ1[0][0], ymin=0, ymax=self.coordXYQ1[0][1], colors='k', linestyles='dashed') #PA
        axis[0, 1].hlines(y=self.coordXYQ1[0][1], xmin=0, xmax=self.coordXYQ1[0][0], colors='k', linestyles='dashed') #PT
        axis[0, 1].hlines(y=self.coordXYValleyQ1[0][1], xmin=self.coordXYValleyQ1[0][0], xmax=self.coordXYQ1[0][0], colors='red', linestyles='dashed') #RD
        axis[0, 1].hlines(y=self.coordXYValleyQ1[0][1], xmin=0, xmax=self.coordXYValleyQ1[0][0], colors='blue', linestyles='dashed') #LAT
        
        axis[0, 1].plot(self.xAxisQ1[self.closest_minsQ1], self.yQ1[self.closest_minsQ1],'o', label = 'closest mins')
        axis[0, 1].grid()

        
        #---------------Plot Data da Questão 2---------------

        axis[1, 0].set_title('Periodo da Questão nº 2')
        axis[1, 0].set_ylabel('EDA (uS)')
        axis[1, 0].set_xlabel('Segundos')
        axis[1, 0].plot(self.xAxisQ2, self.yQ2, 'tab:green')
        axis[1, 0].plot(self.xAxisQ2[self.peaksQ2], self.yQ2[self.peaksQ2], "x")
        
        axis[1, 0].vlines(x=self.coordXYQ2[0][0], ymin=0, ymax=self.coordXYQ2[0][1], colors='k', linestyles='dashed') #PA
        axis[1, 0].hlines(y=self.coordXYQ2[0][1], xmin=0, xmax=self.coordXYQ2[0][0], colors='k', linestyles='dashed') #PT
        axis[1, 0].hlines(y=self.coordXYValleyQ2[0][1], xmin=self.coordXYValleyQ2[0][0], xmax=self.coordXYQ2[0][0], colors='red', linestyles='dashed') #RD
        axis[1, 0].hlines(y=self.coordXYValleyQ2[0][1], xmin=0, xmax=self.coordXYValleyQ2[0][0], colors='blue', linestyles='dashed') #LAT
        
        axis[1, 0].plot(self.xAxisQ2[self.closest_minsQ2], self.yQ2[self.closest_minsQ2],'o', label = 'closest mins')
        axis[1, 0].grid()

        
        
        #---------------Plot Data da Questão 3---------------

        axis[1, 1].set_title('Periodo da Questão nº 3')
        axis[1, 1].set_xlabel('Segundos')
        axis[1, 1].plot(self.xAxisQ3, self.yQ3, 'tab:red')
        axis[1, 1].plot(self.xAxisQ3[self.peaksQ3], self.yQ3[self.peaksQ3], "x")
        
        axis[1, 1].vlines(x=self.coordXYQ3[0][0], ymin=0, ymax=self.coordXYQ3[0][1], colors='k', linestyles='dashed') #PA
        axis[1, 1].hlines(y=self.coordXYQ3[0][1], xmin=0, xmax=self.coordXYQ3[0][0], colors='k', linestyles='dashed') #PT
        axis[1, 1].hlines(y=self.coordXYValleyQ3[0][1], xmin=self.coordXYValleyQ3[0][0], xmax=self.coordXYQ3[0][0], colors='red', linestyles='dashed') #RD
        axis[1, 1].hlines(y=self.coordXYValleyQ3[0][1], xmin=0, xmax=self.coordXYValleyQ3[0][0], colors='blue', linestyles='dashed') #LAT
        
        axis[1, 1].plot(self.xAxisQ3[self.closest_minsQ3], self.yQ3[self.closest_minsQ3],'o', label = 'closest mins')
        axis[1, 1].grid()

        
        
        #Ajusta e mostra Array de graficos
        plt.tight_layout()
        plt.show()
        
        
        
        
    def onePlotData(self):
        
        #Divisão das diferentes etapas
        plt.axvline(self.timeToRest, linewidth=2, color='k', linestyle='--')
        plt.axvline((self.timeToRest + self.timeToQuestion), linewidth=2, color='r', linestyle='--')
        plt.axvline((self.timeToRest + (self.timeToQuestion*2)), linewidth=2, color='r', linestyle='--')
        
        plt.xlabel('Segundos')
        plt.ylabel('EDA (uS)')
        plt.title('Periodo total do teste')
        plt.plot(self.xAxisTotal, self.yTotal)
        plt.plot(self.xAxisTotal[self.peaksTotal], self.yTotal[self.peaksTotal], "x")
        plt.plot(self.xAxisTotal[self.closest_minsTotal], self.yTotal[self.closest_minsTotal],'o', label = 'closest mins')
        
        
        plt.tight_layout()
        plt.show()
    
    
    
    
    
    
    
    
    
    
    
    
    
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowUi = QtWidgets.QMainWindow()
    ui = Ui_MainWindowUi()
    ui.setupUi(MainWindowUi)
    MainWindowUi.show()
    sys.exit(app.exec_())