# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import threading
from PyQt5.QtWidgets import *
from ui.PlotWindowConfig import Ui_PlotWindow
from dataReader import *


class Ui_MainWindowUi(object):        
    def setupUi(self, MainWindowUi):
        MainWindowUi.setObjectName("MainWindowUi")
        MainWindowUi.resize(1094, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindowUi)
        self.centralwidget.setObjectName("centralwidget")
        self.labelDetectorMentiras = QtWidgets.QLabel(self.centralwidget)
        self.labelDetectorMentiras.setGeometry(QtCore.QRect(80, 30, 921, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelDetectorMentiras.setFont(font)
        self.labelDetectorMentiras.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDetectorMentiras.setObjectName("labelDetectorMentiras")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 90, 1041, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 16, 1011, 311))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.inputPergunta = QtWidgets.QLabel(self.tab_2)
        self.inputPergunta.setGeometry(QtCore.QRect(10, 110, 1011, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputPergunta.setFont(font)
        self.inputPergunta.setAlignment(QtCore.Qt.AlignCenter)
        self.inputPergunta.setObjectName("inputPergunta")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(20, 20, 326, 25))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnBitalinoConnect = QtWidgets.QPushButton(self.widget)
        self.btnBitalinoConnect.setObjectName("btnBitalinoConnect")
        self.gridLayout_2.addWidget(self.btnBitalinoConnect, 0, 0, 1, 1)
        self.btnStart = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.gridLayout_2.addWidget(self.btnStart, 0, 1, 1, 1)
        self.btnPergAnterior = QtWidgets.QPushButton(self.widget)
        self.btnPergAnterior.setObjectName("btnPergAnterior")
        self.gridLayout_2.addWidget(self.btnPergAnterior, 0, 2, 1, 1)
        self.btnPergSeguinte = QtWidgets.QPushButton(self.widget)
        self.btnPergSeguinte.setObjectName("btnPergSeguinte")
        self.gridLayout_2.addWidget(self.btnPergSeguinte, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit.setGeometry(QtCore.QRect(240, 50, 531, 221))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindowUi.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowUi)
        self.statusbar.setObjectName("statusbar")
        MainWindowUi.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowUi)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindowUi)
        
        self.countdownTimer = QtCore.QTimer()
        self.btnBitalinoConnect.clicked.connect(self.startBitalinoPlotting)
        self.btnStart.clicked.connect(lambda:self.start_timer("countdown"))
        
        
        self.i = 0        
        self.btnPergSeguinte.clicked.connect(lambda:self.startWithQuestions())
        
                
    
    def startBitalinoPlotting(self):
        plotWin = Ui_PlotWindow()
        self.stop_threads = False
        # Add the callbackfunc to ..
        self.myDataLoop = threading.Thread(name = 'myDataLoop', target = dataSendLoop, daemon = True, args = (plotWin.addData_callbackFunc, self.stop_threads))
        self.myDataLoop.start()
        return
    
    
    def start_timer(self, funcao):
        self.inputPergunta.setText("Respire fundo e concentre-se...")
        
        self.countdown = 15
        self.countdownTimer.timeout.connect(self.update_clock)
        self.countdownTimer.start(1000) # fires every 1000ms = 1s
            

    def update_clock(self):
        
        if (self.countdown >= 0):
            #update a clock label that shows the countdown value
            self.inputPergunta.setText(str(self.countdown))
            #or just print the vaule for now
            print(self.countdown)
            
        self.countdown -= 1
        
            
    
    
    def startWithQuestions(self):
        self.questions = ["Garante à máquina da verdade que não copiou no teste de Bioinstrumentação?",
                    "Garante à máquina da verdade que nunca copiou num teste das UC's do professor Nuno Dias?",
                    "Garante à máquina da verdade que nunca falou mal do professor Nuno Dias?"
                    ]
        self.qtdQuestions = len(self.questions)
        
        if(self.i <= self.qtdQuestions):
            self.inputPergunta.setText(self.questions[self.i])
            self.i += 1
        else:
            self.inputPergunta.setText("O seu teste terminou, aguarde os resultados!")

            

    

    def retranslateUi(self, MainWindowUi):
        _translate = QtCore.QCoreApplication.translate
        MainWindowUi.setWindowTitle(_translate("MainWindowUi", "Detector de Mentiras"))
        self.labelDetectorMentiras.setText(_translate("MainWindowUi", "Detector de Mentiras"))
        self.textEdit_2.setHtml(_translate("MainWindowUi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Instruções para o teste:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1. Coloque os elétrodos na palma da mão</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2. Respire normalmente e tente abstrair-se do que lhe rodeia</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3. Serão usados 15seg antes de iniciar o teste, para fazer criar um padrão da sua resposta galvánica.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindowUi", "Introdução"))
        self.inputPergunta.setText(_translate("MainWindowUi", ""))
        self.btnBitalinoConnect.setText(_translate("MainWindowUi", "Bitalino Connect"))
        self.btnStart.setText(_translate("MainWindowUi", "Começar"))
        self.btnPergAnterior.setText(_translate("MainWindowUi", "Anterior"))
        self.btnPergSeguinte.setText(_translate("MainWindowUi", "Próxima"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindowUi", "Perguntas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindowUi", "Resultados"))
        self.textEdit.setHtml(_translate("MainWindowUi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Projecto desenvolvido no âmbito da unidade curricular de </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Bioinstrumentação</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Realizado por:</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">a20... - Élson Simões</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">a20.... - Óscar Araújo</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">a21674 - Rui Lopes</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindowUi", "Sobre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowUi = QtWidgets.QMainWindow()
    ui = Ui_MainWindowUi()
    ui.setupUi(MainWindowUi)
    MainWindowUi.show()
    sys.exit(app.exec_())
